name: Build

on:
  push:
    branches: [ main , dev]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    
    - name: build mvn fruit-consumer-java
      run: |
        cd fruit-consumer-java
        mvn package
    - name: build docker image fruit-consumer-java
      run: |
        cd fruit-consumer-java
        docker build -t fruit-consumer-java -f ./src/main/docker/Dockerfile.jvm .

    - name: build docker image fruit-consumer-azurefunction
      run: |
        cd fruit-consumer-azurefunction
        docker build -t fruit-consumer-azurefunction .

    - name: build docker image fruit-producer
      run: |
        cd fruit-producer
        docker build -t fruit-producer .