name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./fruit-producer
        platforms: linux/amd64
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/fruit-producer:latest
          ghcr.io/${{ github.repository_owner }}/fruit-producer:${{ github.event.release.tag_name }}

    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./fruit-consumer
        platforms: linux/amd64
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/fruit-consumer:latest
          ghcr.io/${{ github.repository_owner }}/fruit-consumer:${{ github.event.release.tag_name }}
