name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./fruit-producer
        platforms: linux/amd64
        push: true
        tags: |
          ${{ github.repository_owner }}/fruit-producer:latest
          ${{ github.repository_owner }}/fruit-producer:${{github.run_number}}
          ghcr.io/${{ github.repository_owner }}/fruit-producer:latest
          ghcr.io/${{ github.repository_owner }}/fruit-producer:${{github.run_number}}
